controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

root_route_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /en
        permanent: true